### ISSUE TITLE
DrawList_CornerFlags not applied correctly

### ISSUE THREAD

**Issue by piretro** [MultiPain/Gideros_ImGui#5]
Hi, 
https://github.com/MultiPain/Gideros_ImGui#corner_flags 
every **CornerFlag** except **_Closed** and **_None** in addRect and addRectFilled is applied as ImGui.DrawFlags_RoundCornersAll 

Thank you!

**Comment by piretro** [comment]
*Not always, need to investigate further if it is my fault. closing this right now.

**Comment by mokalux** [comment]
you forgot to close it piretro, I stumbled upon your issue while documenting Gideros wiki 😄
